name: Build and push the image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_UNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - id: prep
        run:
          echo ::set-output name=hash::$(git rev-parse HEAD)

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          pull: false
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/jhu-idc/mariadb/perms_init_container:latest
            ghcr.io/jhu-idc/mariadb/perms_init_container:${{ steps.prep.outputs.hash }}
          labels:
            org.opencontainers.image.source=https://github.com/jhu-idc/mariadb_perms_init_container
            org.opencontainers.image.title=perms_init_container

